return {
  "olexsmir/gopher.nvim",
  ft = "go",
  cmd = {
    "GoTagAdd",
    "GoTagRm",
    "GoTagClear",
    "GoIfErr",
    "GoCmt",
    "GoImpl",
    "GoJson",
    "GoTestAdd",
    "GoTestsAll",
    "GoTestsExp",
    "GoMod",
    "GoGet",
    "GoWork",
    "GoGenerate",
    "GoInstallDeps",
    "GoInstallDepsSync",
  },
  opts = {},
}
